name: JavaEE CI/CD Pipeline

on:
  push:
    branches:
      - dev  # Adjust to the branches you want to trigger CI/CD on

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: megacity_test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptopenjdk'
          version: '21'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Set up environment variables
      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=jdbc:mysql://127.0.0.1:3306/megacity_test_db" >> $GITHUB_ENV
          echo "DATABASE_USER=root" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=1234" >> $GITHUB_ENV

      # Install dependencies (Maven build)
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run MySQL setup script (if any)
      - name: Set up MySQL database
        run: |
          mysql -h 127.0.0.1 -u root -p1234 megacity_test_db < src/test/resources/megacity_test_db.sql

      # Run tests
      - name: Run tests
        run: mvn test -DskipTests=false

      # Archive test results
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/test-classes/test-results/
