name: Build and Test with MySQL

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Test with MySQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set up MySQL Database
        run: |
          sudo systemctl restart mysql  # Restart MySQL to ensure it's fresh
          sudo mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';"
          sudo mysql -uroot -p1234 -e "CREATE DATABASE megacity_test_db;"
          sudo mysql -uroot -p1234 -e "FLUSH PRIVILEGES;"

      - name: Check MySQL Status
        run: sudo systemctl status mysql || true

      - name: Run Database Migration Script
        run: |
          mysql -uroot -p1234 megacity_test_db < src/main/resources/megacity_test_db.sql

      - name: Run Tests
        run: mvn clean test
