name: JavaEE CI/CD Pipeline

on:
  push:
    branches:
      - dev  # Adjust to your desired branch for testing

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: megacity_test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Set up environment variables
      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=jdbc:mysql://127.0.0.1:3306/megacity_test_db" >> $GITHUB_ENV
          echo "DATABASE_USER=root" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=1234" >> $GITHUB_ENV

      # Initialize MySQL database
      - name: Initialize MySQL database megacity_test_db
        run: |
          mysql -h 127.0.0.1 -u root -p1234 megacity_test_db < src/test/resources/megacity_test_db.sql || { echo "Failed to run megacity_test_db.sql"; exit 1; }

      # Show tables in database
      - name: Show tables in database
        run: |
          mysql -h 127.0.0.1 -u root -p1234 megacity_test_db -e "SHOW TABLES;" || { echo "Failed to show tables"; exit 1; }

      # Build and run specific test with Maven
      - name: Build and run specific test with Maven
        run: mvn clean test -Dtest=TestTempory
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DATABASE_USER: ${{ env.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}

      # Upload test results
      - name: Upload test results
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/