name: Build and Test with MySQL

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Test with MySQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Install MySQL manually
      - name: Install MySQL
        run: |
          sudo systemctl start mysql
          sudo mysql -e "CREATE DATABASE megacity_test_db;"
          sudo mysql -e "CREATE USER 'root'@'%' IDENTIFIED BY '1234';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON megacity_test_db.* TO 'root'@'%';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      # Verify MySQL is running
      - name: Check MySQL Status
        run: sudo systemctl status mysql || true

      # Run SQL script
      - name: Run Database Migration Script
        run: |
          mysql -u root -p1234 megacity_test_db < src/main/resources/megacity_test_db.sql

      - name: Run Tests
        run: mvn clean test
