name: Build and Test with MySQL

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: megacity_test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Wait for MySQL to be ready
      - name: Wait for MySQL to start
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL to be available..."
            sleep 2
          done
          echo "MySQL is ready!"

      # Run Database Migration Script
      - name: Import Database Schema
        run: |
          mysql -h 127.0.0.1 -u root -p1234 megacity_test_db < src/main/resources/megacity_test_db.sql

      - name: Run Tests
        run: mvn clean test
