name: JavaEE CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: megacity_test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Set up environment variables
      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=jdbc:mysql://127.0.0.1:3306/megacity_test_db" >> $GITHUB_ENV
          echo "DATABASE_USER=root" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=1234" >> $GITHUB_ENV

      # Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root -p1234 --silent; then
              echo "MySQL is ready!"
              break
            else
              echo "Waiting for MySQL to be ready..."
              sleep 5
            fi
          done
          if [ $i -eq 30 ]; then
            echo "Error: MySQL did not start in time!"
            exit 1
          fi

      # Run Flyway migrations to initialize the database
      - name: Initialize database with Flyway
        run: mvn flyway:migrate
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DATABASE_USER: ${{ env.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}

      # Verify database initialization (optional)
      - name: Show tables in database
        run: |
          mysql -h 127.0.0.1 -u root -p1234 megacity_test_db -e "SHOW TABLES;" || { echo "Failed to show tables"; exit 1; }

      # Build without tests with Maven
      - name: Build without tests with Maven
        run: mvn clean install -DskipTests
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DATABASE_USER: ${{ env.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}

      # Upload build artifacts
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/*.war