name: Build and Test with MySQL

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Test with MySQL
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: megacity_test_db
          MYSQL_USER: root
          MYSQL_PASSWORD: 1234
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h "127.0.0.1" --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run Database Migration Script
        run: |
          mysql -h 127.0.0.1 -u root -p1234 megacity_test_db < src/main/resources/megacity_test_db.sql

      - name: Run Tests
        run: mvn clean test
