name: Build Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Eclipse Temurin (formerly AdoptOpenJDK)
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
