name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Tomcat (Production)
        run: |
          scp target/*.war ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER }}:/opt/tomcat/webapps/mega-city-cab-service.war
          ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER }} "sudo systemctl restart tomcat"
